default:
  image: node
  
build-job:
  stage: build
  script:
    - npm run build

test-job:
  stage: test
  script:
    - npm test -- --coverage --watchAll=false

deploy-job:
  stage: deploy
  script:
    - echo "Deploy"
