image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-job:
  stage: build
  script:
    - npm install -q --no-color --no-progress
    - npm run build

test-job:
  stage: test
  script:
    - npm install -q --no-color --no-progress
    - npm test -- --coverage --watchAll=false

deploy-job:
  stage: deploy
  script:
    - echo "Deploy"
