image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

build-job:
  stage: build
  script:
    - npm install -q --no-color --no-progress
    - npm run build

test-job:
  stage: test
  script:
    - npm test -- --coverage --watchAll=false

deploy-job:
  stage: deploy
  script:
    - echo "Deploy"
